import { Dimensions, StyleSheet } from "react-native";
import { theme } from "./theme";

export const styleFactory = () => {
  return StyleSheet.create({
    headerStyle: {
      fontSize: 30,
      backgroundColor: theme.sectionHeadingColor,
      color: "white",
    },
    screen: {
      flex: 1,
      backgroundColor: theme.backgroundColorLight,
      //   paddingVertical: 20,
    },
    title: {
      fontFamily: theme.fontBold,
      fontSize: 44,
      color: theme.text,
      marginVertical: 15,
    },
    sectionHeading: {
      fontSize: theme.sectionHeadingSize,
      fontFamily: theme.font,
      marginVertical: 10,
      color: theme.sectionHeadingColor,
    },

    container: {
      backgroundColor: theme.backgroundColorLight,
      paddingVertical: 15,
      paddingHorizontal: 15,
      // borderRadius: 10,
      marginVertical: 12,
      marginHorizontal: 15,
      // borderWidth: 1,
      // borderColor: "rgba(0,0,0,0.05)",
      // elevation: 1,
      // shadowColor: "#000",
      // shadowOffset: { width: 0, height: 4 },
      // shadowOpacity: 0.12,
      // shadowRadius: 8,
    },
    text: {
      fontSize: theme.fontSize,
      color: theme.text,
      fontFamily: theme.font,
      marginVertical: 10,
      textAlign: "justify",
    },
    aboutCard: {
      paddingVertical: 15,
      paddingHorizontal: 20,
      backgroundColor: theme.backgroundColorLight,
      margin: 15,
      marginTop: 0,
      borderRadius: 5,
      elevation: 1,
      borderWidth: 1,
      borderColor: "rgba(0,0,0,0.05)",
      // shadowColor: "#000",
      // shadowOffset: { width: 0, height: 4 },
      // shadowOpacity: 0.12,
      // shadowRadius: 8,
    },
    companyName: {
      fontFamily: "Delius_400Regular",
      color: theme.sectionHeadingColor,
    },
    stackButton: {
      backgroundColor: theme.backgroundColorLight,
      paddingHorizontal: 5,
      paddingVertical: 20,
      justifyContent: "center",
      flex: 1,
    },
    stackButtonText: {
      textAlign: "center",
      color: theme.text,
      fontFamily: theme.fontBold,
    },
    swipeDotIndicatorContainer: {
      width: Dimensions.get("window").width,
      justifyContent: "center",
      marginVertical: 10,
      flexDirection: "row",
      gap: 10,
    },
    swipeDotActive: {
      width: 10,
      height: 10,
      backgroundColor: theme.sectionHeadingColor,
      borderRadius: 20,
    },
    swipeDotInActive: {
      width: 7,
      height: 7,
      borderRadius: 20,
    },
    whoAreYouOption: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      gap: 10,
      backgroundColor: "white",
      width: 350,
      // elevation: 1,
      borderWidth: 1,
      borderColor: theme.red,
      // elevation: 3,
      // shadowColor: "#000",
      // shadowOffset: { width: 0, height: 2 },
      // shadowOpacity: 0.1,
      // shadowRadius: 4,
      paddingVertical: 10,
      paddingHorizontal: 10,
      borderRadius: 5,
    },
    whoAreYouOptionText: {
      color: theme.red,
      fontFamily: theme.fontBold,
      fontSize: theme.fontSize,
      textAlign: "center",
    },
    inputField: {
      backgroundColor: theme.backgroundColorLight,
      paddingHorizontal: 10,
      paddingVertical: 5,
      borderRadius: 5,
      borderWidth: 1,
      color: theme.text,
      fontSize: 16,
      borderColor: theme.backgroundColorDark,
    },
  });
};
